{% set name = "satlaspretrain-models" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/satlaspretrain_models-{{ version }}.tar.gz
  sha256: bda93e30494372e59d2af604683143dec13d19712d953d94dc466d34bb24559c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - pytorch >=2.1.0
    - torchvision >=0.16.0
    - requests
    - matplotlib-base

test:
  imports:
    - satlaspretrain_models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/allenai/satlaspretrain_models
  summary: A simple package that makes it easy to load remote sensing foundation models for downstream use cases.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
